from imprt1_file import table,student,teacher,sum
print ("table of 9")
table(9)
print("table of 5")
table(5)
print("number addition")
print(sum(5,6))
print("student class")
s = student("John", 20)
j = student("Jane", 22)
t = teacher("Mr. Smith", "Math")
z = teacher("Ms. Johnson", "Science")
s.display()
j.display()
print("teacher class")
t.display()
z.display()
